module.exports = [
    "Monsieur et Madame Ritlecul ont un fils, comment s'appelle-il ? Samy. Samy Ritlecul.",
    "Quelle est la différence entre une grosse bonne femme et des pantoufles ? Aucune, on est bien dedans mais on sort pas avec.",
    "Qui est ce qui court plus vite qu'Usain Bolt ? Un Somalien avec un ticket resto.",
    "Quelle est la différence entre un trader et un acteur porno ? Le trader a des actions en bourse alors que l’autre a les bourses en action",
    "Vous connaissez le point commun entre un gynécologue et un pizzaiolo ? Ils peuvent la sentir mais pas la bouffer !",
    "Un chien et un homme son sur un bateau. Le chien pète, l'homme tombe à l'eau et se noie. Quelle est la race du chien ? Un pékinois.",
    "Qu'est-ce qu'une manifestation d'aveugles ? Un festival de Cannes",
    "Pourquoi Napoléon n'a pas acheté une maison ? Parce qu'il avait déjà un bon appart",
    "Que dit Frodon devant sa maison? C'est là que j'Hobbit...",
    "Quel est le point commun entre une église et une petite fille ? Les seins sont à l'intérieur.",
    "Qu'est-ce qu'un tube de colle avec une cape ? SuperGlue.",
    "Le Père Noël est le seul barbu qui peut survoler les Etats-Unis sans problèmes.",
    "Quel est le saint patron des rouquins ? Oliver, car l'ange Oliver protège les roux.",
    "Qu'a dit Tarzan avant de mourir ?  - Qui a chié sur ma Liiiiiaaaannnneeeeee ?",
    "Qu'est-ce qui a 4 pattes et un bras ?  Un pitbull dans un jardin d'enfants.",
    "C'est un pistolet qui s'approche d'une mitraillette et qui lui dit: - Ca fait longtemps que tu bégayes ?",
    "Pourquoi les anglais n’aiment pas les grenouilles ? Car elles font le thé tard.",
    "Quelle est la différence entre un galet et un routier? Le galet, plus il roule, plus il est poli !",
    "Quelle est la différence entre une Merco et une Lada ? Dans la Merco t'as l'air conditionné, et dans la Lada t'as l'air con",
    "Quelle est la différence entre une femme et une blonde ? La moto c'est une Suzuki et la blonde c'est une sucekiki",
    "Quel est le fruit préféré des militaires ? La grenade.",
    "Qu'est-ce qui est jaune et qui ~~attend~~ court vite ? Un citron pressé !",
    "C'est l'histoire d'un pinguin qui respirait par le cul. Un jour il s'assoit, il meurt.",
    "C'est un zoophile qui rentre dans un bar... C'est tout.",
    "Comment donner plus de liberté à une femme ? - En agrandissant la cuisine.",
    "C'est un aveugle qui rentre dans un bar, puis dans une table, puis dans une chaise...",
    "Que dit un aveugle qui touche du papier de verre ? Mince, c'est écrit trop petit !",
    "Comment appelle-t-on un lecteur de DVD cannibale ? Hannibal lecteur.",
    "Qui y a t'il de pire qu'un bébé dans une poubelle ? Un bébé dans deux poubelles.",
    "Pourquoi le saut a l'élastique est-il formellement interdit aux non-voyants ? Parceque ça fait trop peur au chien.",
    "Comment on appelle une Lada avec un toit ouvrant ? Une poubelle",
    "Qu'est-ce qui a deux bosses et qu'on trouve au pôle Nord ? Un chameau qui s'est perdu !",
    "Quel est le coquillage le moins lourd ? La palourde",
    "Pourquoi les Indiens mettent-ils tout leur argent en bourse ? Parce que ça rapporte des sioux !",
    "Vous savez ce qui passe par la tête d'un moustique lorsqu'il s'écrase sur un pare-brise ? Son trou du balle !",
    "Pourquoi les pêcheurs ne sont jamais gros ? Parce qu'ils surveillent leur ligne.",
    "Vous connaissez l'histoire du lit vertical ? C'est une histoire à dormir debout.",
    "Comment appelle-t-on un combat entre un haricot et une carotte ? Un bon duel.",
    "Comment appelle-t-on un indien dans l'eau ? Un Sioux Marin.",
    "C'est l'histoire d'un schtroumpf qui court, qui tombe, et qui se fait un bleu.",
    "Comment s'appelle la femelle du hamster ? Amsterdam.",
    "Quel bruit fait un esquimau qui se noit ? Iglou, iglou, iglou !",
    "Pour un cannibale, une femme enceinte c'est un peu comme un Kinder Surprise.",
    "Pourquoi Mickey Mousse ? Parce que Mario brosse.",
    "Comment appelle-t-on un boomerang qui ne revient pas ? Un bâton",
    "C'est Abdul qui rencontre un pote : - ça va mecque ?",
    "Que ne faut-il jamais dire à un antiquaire ? - Alors, quoi de neuf ?"
]