module.exports = {
    faux: 'cest_pas_faux1.mp3',
    bite: 'petite_bite.mp3',
    merde: 'cest_de_la_merde.mp3',
    cuillere: 'cuillere.mp3',
    ambiance: 'ambiance.mp3',
    interprete: 'interprete.mp3',
    graines: 'graines.mp3',
    mecreant: 'mecreant.mp3',
    gros : 'on_en_a_gros.mp3',
    questcedire : 'qu-est_ce_dire_que_ceci.mp3',
    tut: 'petite_corne.mp3',
    tg: 'tu_la_fermes_definitivement.mp3',
    nils: 'nils.mp3',
    philippe: 'philippe.mp3',
    ballec: 'ballec.mp3',
    ah: 'ah.mp3',
    ahah: 'nelson.mp3',
    meurs: 'pourriture.mp3',
    fire: 'feu.mp3'
}